# Assignment 1 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [306]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

#You have to create few files with dummy data of your own choice as shown above.



# Step 2 Traverse Directories


 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [289]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [290]:
#Your code starts here   
path = os.getcwd()
#print(path)
dir_list = os.listdir(path)
print(dir_list)
count=0
for keys in dir_list:
    if(keys=="IRS.ipynb"):
        continue
    if(keys!="IRS.ipynb"):
        files_dict[keys]=count
        count=count+1
    
print(files_dict)
file_count=count

#Your code ends here       

['fil2.txt', 'file1.txt', 'file3.txt', 'IRS.ipynb']
{'fil2.txt': 0, 'file1.txt': 1, 'file3.txt': 2}


Displaying the count of files.

In [291]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [292]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'fil2.txt': 0, 'file1.txt': 1, 'file3.txt': 2}


# Step 3 Extract Unique Vocabulary

In [293]:
# write code to print all the unique words in every file and store them in a set

In [294]:
#Your code starts here    
for key in files_dict:
    fhandler = open(key, "r")
    file_contents=fhandler.read().lower()
    fhandler.close()
    file_contents=file_contents.split()
    for index, word in enumerate(file_contents):
        if word.isalpha():
            continue 
        if word[:-1].isalpha():
            file_contents[index]=word[:-1]
    unique_word_set=unique_word_set|set(file_contents)
print(unique_word_set)



   
    
    


{'is', 'studying', 'name', 'raza', 'pucit', 'assignment', 'my', 'a', 'student', 'building', 'ai', 'ir', 'haseeb', 'im'}


### Expected Output


<img src="4.png"/>

# Step 4 Create Term Document Matrix


Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [295]:
# Create Term doc matrix such that colmns will be unique words and all the files will be rows
# Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [296]:
#Your code starts here
#shape = (file_count, len(unique_word_set))
#a = np.zeros(shape)
#print(a)
shape = (file_count, len(unique_word_set))
#print(file_count, type(file_count))
#print(len(unique_word_set))
#print(shape)
term_documen_matrix = np.zeros(shape)
#print(a)
#print(unique_word_set)
unique_word_dict=dict()
count=0
for element in unique_word_set:
    unique_word_dict[element]=count
    count=count+1
print(unique_word_dict)
#Your code ends here

{'is': 0, 'studying': 1, 'name': 2, 'raza': 3, 'pucit': 4, 'assignment': 5, 'my': 6, 'a': 7, 'student': 8, 'building': 9, 'ai': 10, 'ir': 11, 'haseeb': 12, 'im': 13}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [297]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory

In [298]:
#Your code starts here 
current_file_count=0 
print(unique_word_dict)  
for key in files_dict:
    
    fhandler = open(key, "r")
    file_contents=fhandler.read().lower()
    fhandler.close()
    file_contents=file_contents.split()
    for words in file_contents:
        term_documen_matrix[current_file_count][unique_word_dict[words]]=1
    current_file_count=current_file_count+1
print(term_documen_matrix)

#Your code ends here

{'is': 0, 'studying': 1, 'name': 2, 'raza': 3, 'pucit': 4, 'assignment': 5, 'my': 6, 'a': 7, 'student': 8, 'building': 9, 'ai': 10, 'ir': 11, 'haseeb': 12, 'im': 13}
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0.]]


### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [299]:
# For user query make a column vector of length of all the unique words present in a set

In [300]:
#Your code starts here
query_matrix=np.zeros((len(unique_word_set),1)) 
print(query_matrix)

#Your code ends here

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

<img src="7.png"/>

In [301]:
query = input("\nWrite something for searching  ")


# Check every word of query if it exists in the set of unique words or not
# If exixts then increment the count of that word in word dictionary


In [302]:
#Your code starts here    
print(query)
query=query.lower()
query=query.split()
print(query)
for word in query:
    if(word in unique_word_set):
        c=unique_word_dict[word]
        print(c)
        query_matrix[c][0]= query_matrix[c][0]+1
        print("incremented once")
print(query_matrix)
#Your code ends here

haseeb is a student
['haseeb', 'is', 'a', 'student']
12
incremented once
0
incremented once
7
incremented once
8
incremented once
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]]


### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [303]:
#Your code starts here  
resultant_matrix=np.dot(term_documen_matrix,query_matrix)
print(resultant_matrix)
max_value=float(max(resultant_matrix))
print(max_value)
file_number=-1

for rows in resultant_matrix:
    file_number=file_number+1
    if rows==max_value:
        matched_file=rows
        break
print(file_number)   

#Your code ends here

[[0.]
 [4.]
 [2.]]
4.0
1


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [304]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [305]:
#Your code starts here   
count=-1 
for key in files_dict:
    count=count+1
        
    fhandler = open(key, "r")
    if file_number==count:
        file_contents=fhandler.read()
        print(file_contents)
        break
    if file_number!=count:
        continue
    fhandler.close()
#Your code ends here

my name is haseeb raza
im a pucit student



Congratulations Now you are able to build your own small IRS.